#Project Paths 
paths:
  base_dir: "./data/"
  train_dir: "./data/Training/"
  val_dir: "./data/Validation/"
  models_dir: "./models/"
  outputs_dir: "./outputs/"

#Classes
classes:
  num_classes: 19
  names:
    - Generic Valve
    - Needle Valve
    - Ball Valve
    - Globe Valve
    - Gate Valve
    - Field Instruments
    - Platform Control System
    - Control Systems
    - Local Panel Gauge Board
    - Reducer
    - Flange
    - 5-Way Manifold
    - Core Strainer
    - Butterfly Valve
    - Pressure Reducing Regulator
    - Back Pressure Reducing Regulator
    - Pressure Control Valve
    - Fire-Fighting System Nozzle
    - Connector

#Inference Parameters 
inference:
  confidence_threshold: 0.5
  nms_threshold: 0.4

#MLflow Settings 
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "digitised_pid_mlops"

